version: '3.9'

services:

  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - ELASTICSEARCH_HOST=${ES_HOST}:${ES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - ${ES_PORT}:${ES_PORT}
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: es_adminer
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}

  backend:
    build: ./backend/
    container_name: backend
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
      - elasticsearch
    volumes:
      - ./backend:/backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
